os: linux
dist: trusty
language: java
install: true
jdk: openjdk8
cache:
  directories:
  - $HOME/.m2
jobs:
  include:
  - stage: Core
    script: mvn -pl lightning-core clean install -DmockS3
  - stage: Clients
    name: "Lambda"
    script: mvn -pl lightning-aws-lambda clean verify
  - script: mvn -pl jmeter-lightning-maven-plugin clean verify
    name: "Maven"
