os: linux
dist: trusty
language: java
install: true
jdk: openjdk8
cache:
  directories:
  - $HOME/.m2
jobs:
  include:
  - stage: lightning-core
    script: mvn -pl lightning-core clean install -DmockS3
  - stage: lightning-aws-lambda
    script: mvn -pl lightning-aws-lambda clean verify
